services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - /Users/justin/media-server/sonarr/config:/config
      - /Volumes/NAS/media/movies:/movies
      - /Volumes/NAS/media/tv:/tv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    ports:
      - 8989:8989
