services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    volumes:
      - /Users/justin/media-server/prowlarr/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    ports:
      - 9696:9696
