services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    volumes:
      - /Users/justin/media-server/jellyseerr/config:/config
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Denver
    ports:
      - 5055:5055
