services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    network_mode: host
    restart: unless-stopped
    volumes:
      - /Users/justin/media-server/jellyfin/config:/config
      - /Users/justin/media-server/jellyfin/cache:/cache
      - /Volumes/NAS/media/movies:/movies
      - /Volumes/NAS/media/tv:/tv
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    ports:
      - 8096:8096
    extra_hosts:
      - host.docker.internal:host-gateway
